### PR TITLE
Intelligent Spring usage

### PR DESCRIPTION
**Pull request by andyw8**
RSpec 3 introduced the concept of separate `spec_helper.rb` and
`rails_helper.rb` files. This means code which doesn't depend on Rails
can be tested in isolation, without having to load Rails.

However, when using Spring, Rails will always be loaded, meaning you
can accidentally couple your class to Rails without realising it. The
spec will pass when running through Spring, but will fail otherwise:

http://www.andywaite.com/2015/10/11/accidental-rails-coupling/

This PR introduces a new option `g:spec_runner_smart_spring_usage`. When
unset, the behaviour will be as before. When set, it will check which
type of RSpec helper is being used, and bypass Spring accordingly.

### CODE REVIEW

**Comment by gabebw** [comment]
Interesting! I like this.

What do you think about:
- Default to having this on (i.e. a breaking change), but let people turn it off 
- If RSpec 3+ is in the Gemfile, behave "smartly" (like in this PR)
- If RSpec <3 is in the Gemfile, don't behave smartly

**Comment by andyw8** [comment]
I have some concern about that approach since I've seen many apps running RSpec 3 which don't follow the separate helper convention. It's often because the app was originally set up using RSpec 2.x and later upgraded.

A more reliable approach might be to check if both `rails_helper.rb` and `spec_helper.rb` are present?

**Comment by andyw8** [comment]
@gabebw any further thoughts on this?

**Comment by gabebw** [comment]
> A more reliable approach might be to check if both `rails_helper.rb` and `spec_helper.rb` are present?

I like that idea! And I agree that turning it on by default would be a bad idea.

**Pull request closed without merging**
